import type { FlatConfig } from '../types';
import pluginE18e from '@e18e/eslint-plugin';
import pluginStylistic from '@stylistic/eslint-plugin';
import pluginDeMorgan from 'eslint-plugin-de-morgan';
import pluginPerfectionist from 'eslint-plugin-perfectionist';
import pluginRegExp from 'eslint-plugin-regexp';
import pluginUnicorn from 'eslint-plugin-unicorn';
import globals from 'globals';
import { defu } from 'defu';

export interface JavaScriptOptions {
  env?: {
    browser?: boolean;
    node?: boolean;
    webpack?: boolean;
    vitest?: boolean;
    webWorker?: boolean;
    serviceWorker?: boolean;
    greaseMonkey?: boolean;
    webExtensions?: boolean;
    customGlobals?: Record<string, boolean | 'off' | 'readonly' | 'readable' | 'writable' | 'writeable'>;
  };
}

export function javascript(options: JavaScriptOptions = {}): FlatConfig[] {
  type Env = NonNullable<JavaScriptOptions['env']>;
  const env: Env = defu(options.env, {
    browser: true,
    node: true,
  });

  const enabledGlobals =
    Object.entries(env)
      .filter(([_, value]) => value === true)
      .map(([key]) => globals[key as keyof typeof globals])
      .reduce((acc, cur) => ({ ...acc, ...cur }), {});

  return [
    {
      name: 'silvecor/javascript/base',
      languageOptions: {
        ecmaVersion: 'latest',
        globals: {
          ...globals.es2026,
          ...enabledGlobals,
          ...env.customGlobals,
        },
        parserOptions: {
          sourceType: 'module',
          ecmaVersion: 'latest',
          ecmaFeatures: { jsx: true },
        },
      },
      linterOptions: {
        reportUnusedDisableDirectives: true,
      },
      /// keep-sorted
      rules: {
        'array-callback-return': 'error',
        'default-param-last': 'error',
        'dot-notation': ['error', { allowKeywords: true }],
        'grouped-accessor-pairs': 'warn',
        'guard-for-in': 'error',
        'no-alert': 'error',
        'no-await-in-loop': 'warn',
        'no-caller': 'error',
        'no-constant-binary-expression': 'error',
        'no-constant-condition': ['error', { checkLoops: 'allExceptWhileTrue' }],
        'no-constructor-return': 'error',
        'no-empty-pattern': 'error',
        'no-empty-static-block': 'error',
        'no-empty': ['error', { allowEmptyCatch: true }],
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'error',
        'no-extra-boolean-cast': 'error',
        'no-fallthrough': 'error',
        'no-global-assign': 'error',
        'no-implied-eval': 'error',
        'no-labels': 'error',
        'no-lone-blocks': 'error',
        'no-loop-func': 'error',
        'no-loss-of-precision': 'error',
        'no-multi-assign': 'error',
        'no-multi-str': 'error',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-new': 'error',
        'no-nonoctal-decimal-escape': 'warn',
        'no-object-constructor': 'error',
        'no-octal-escape': 'error',
        'no-promise-executor-return': 'error',
        'no-prototype-builtins': 'error',
        'no-restricted-properties': [
          'error',
          {
            property: '__proto__',
            message: 'Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.',
          },
          {
            property: '__defineGetter__',
            message: 'Use `Object.defineProperty` instead.',
          },
          {
            property: '__defineSetter__',
            message: 'Use `Object.defineProperty` instead.',
          },
          {
            property: '__lookupGetter__',
            message: 'Use `Object.getOwnPropertyDescriptor` instead.',
          },
          {
            property: '__lookupSetter__',
            message: 'Use `Object.getOwnPropertyDescriptor` instead.',
          },
        ],
        'no-return-assign': 'error',
        'no-shadow-restricted-names': 'error',
        'no-throw-literal': 'error',
        'no-unassigned-vars': 'error',
        'no-unreachable-loop': 'error',
        'no-unreachable': 'error',
        'no-useless-call': 'error',
        'no-useless-escape': 'error',
        'no-useless-return': 'warn',
        'no-var': 'error',
        'no-with': 'error',
        'object-shorthand': ['error', 'always', { avoidQuotes: true, ignoreConstructors: false }],
        'prefer-const': ['error', { ignoreReadBeforeAssign: true }],
        'prefer-exponentiation-operator': 'error',
        'prefer-promise-reject-errors': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'prefer-template': 'error',
        'symbol-description': 'error',
        'unicode-bom': ['error', 'never'],
        eqeqeq: ['error', 'always', { null: 'ignore' }],
        yoda: ['error', 'never'],
      },
    },
    {
      name: 'silvecor/javascript/extra',
      plugins: {
        unicorn: pluginUnicorn,
        e18e: pluginE18e,
      },
      /// keep-sorted
      rules: {
        'e18e/no-delete-property': 'warn',
        'e18e/no-spread-in-reduce': 'warn',
        'e18e/prefer-array-at': 'warn',
        'e18e/prefer-array-fill': 'error',
        'e18e/prefer-array-from-map': 'warn',
        'e18e/prefer-array-some': 'warn',
        'e18e/prefer-array-to-reversed': 'warn',
        'e18e/prefer-array-to-sorted': 'warn',
        'e18e/prefer-array-to-spliced': 'warn',
        'e18e/prefer-date-now': 'error',
        'e18e/prefer-exponentiation-operator': 'warn',
        'e18e/prefer-includes': 'error',
        'e18e/prefer-inline-equality': 'warn',
        'e18e/prefer-nullish-coalescing': 'warn',
        'e18e/prefer-object-has-own': 'warn',
        'e18e/prefer-static-collator': 'warn',
        'e18e/prefer-string-fromcharcode': 'error',
        'e18e/prefer-timer-args': 'warn',
        'e18e/prefer-url-canparse': 'error',
        'silvecor/top-level-arrow-function': 'warn',
        'unicorn/consistent-assert': 'error',
        'unicorn/consistent-function-scoping': 'error',
        'unicorn/custom-error-definition': 'error',
        'unicorn/error-message': 'warn',
        'unicorn/escape-case': ['error', 'uppercase'],
        'unicorn/new-for-builtins': 'warn',
        'unicorn/no-accessor-recursion': 'error',
        'unicorn/no-array-for-each': 'error',
        'unicorn/no-array-method-this-argument': 'error',
        'unicorn/no-await-expression-member': 'error',
        'unicorn/no-await-in-promise-methods': 'error',
        'unicorn/no-console-spaces': 'warn',
        'unicorn/no-document-cookie': 'error',
        'unicorn/no-for-loop': 'warn',
        'unicorn/no-hex-escape': 'error',
        'unicorn/no-instanceof-builtins': ['error', { strategy: 'loose' }],
        'unicorn/no-invalid-fetch-options': 'error',
        'unicorn/no-invalid-remove-event-listener': 'error',
        'unicorn/no-named-default': 'error',
        'unicorn/no-negated-condition': 'warn',
        'unicorn/no-negation-in-equality-check': 'warn',
        'unicorn/no-new-array': 'warn',
        'unicorn/no-new-buffer': 'error',
        'unicorn/no-object-as-default-parameter': 'warn',
        'unicorn/no-thenable': 'warn',
        'unicorn/no-this-assignment': 'error',
        'unicorn/no-unnecessary-await': 'error',
        'unicorn/no-unreadable-array-destructuring': 'warn',
        'unicorn/no-unreadable-iife': 'warn',
        'unicorn/no-useless-error-capture-stack-trace': 'error',
        'unicorn/no-useless-fallback-in-spread': 'warn',
        'unicorn/no-useless-promise-resolve-reject': 'error',
        'unicorn/number-literal-case': ['error', { hexadecimalValue: 'lowercase' }],
        'unicorn/prefer-array-index-of': 'error',
        'unicorn/prefer-class-fields': 'warn',
        'unicorn/prefer-date-now': 'error',
        'unicorn/prefer-dom-node-append': 'error',
        'unicorn/prefer-dom-node-dataset': 'error',
        'unicorn/prefer-dom-node-remove': 'error',
        'unicorn/prefer-dom-node-text-content': 'error',
        'unicorn/prefer-event-target': 'error',
        'unicorn/prefer-global-this': 'error',
        'unicorn/prefer-import-meta-properties': 'error',
        'unicorn/prefer-keyboard-event-key': 'warn',
        'unicorn/prefer-logical-operator-over-ternary': 'error',
        'unicorn/prefer-math-trunc': 'error',
        'unicorn/prefer-modern-dom-apis': 'error',
        'unicorn/prefer-modern-math-apis': 'error',
        'unicorn/prefer-negative-index': 'warn',
        'unicorn/prefer-node-protocol': 'warn',
        'unicorn/prefer-number-properties': 'error',
        'unicorn/prefer-prototype-methods': 'warn',
        'unicorn/prefer-query-selector': 'warn',
        'unicorn/prefer-reflect-apply': 'error',
        'unicorn/prefer-regexp-test': 'error',
        'unicorn/prefer-response-static-json': 'error',
        'unicorn/prefer-set-has': 'warn',
        'unicorn/prefer-set-size': 'error',
        'unicorn/prefer-string-replace-all': 'warn',
        'unicorn/prefer-string-slice': 'error',
        'unicorn/prefer-string-starts-ends-with': 'error',
        'unicorn/prefer-string-trim-start-end': 'warn',
        'unicorn/throw-new-error': 'error',
      },
    },
    {
      name: 'silvecor/javascript/style',
      plugins: {
        perfectionist: pluginPerfectionist,
        style: pluginStylistic,
        'de-morgan': pluginDeMorgan,
      },
      /// keep-sorted
      rules: {
        'de-morgan/no-negated-conjunction': 'warn',
        'de-morgan/no-negated-disjunction': 'warn',
        'perfectionist/sort-exports': ['warn', { type: 'natural' }],
        'perfectionist/sort-imports': ['warn', {
          groups: [
            'type',
            ['parent-type', 'sibling-type', 'index-type', 'internal-type'],
            'builtin',
            'external',
            'internal',
            ['parent', 'sibling', 'index'],
            'side-effect',
            'object',
            'unknown',
          ],
          newlinesBetween: 'ignore',
          type: 'natural',
        }],
        'perfectionist/sort-named-exports': ['warn', { type: 'natural' }],
        'perfectionist/sort-named-imports': ['warn', { type: 'natural' }],
        'style/array-bracket-spacing': ['warn', 'never'],
        'style/arrow-parens': ['warn', 'as-needed'],
        'style/arrow-spacing': 'warn',
        'style/block-spacing': 'warn',
        'style/brace-style': ['warn', '1tbs', { allowSingleLine: true }],
        'style/comma-dangle': ['warn', 'always-multiline'],
        'style/comma-spacing': 'warn',
        'style/comma-style': ['warn', 'last'],
        'style/computed-property-spacing': ['warn', 'never', { enforceForClassMembers: true }],
        'style/dot-location': ['warn', 'property'],
        'style/eol-last': 'warn',
        'style/function-call-argument-newline': ['warn', 'consistent'],
        'style/function-call-spacing': ['warn', 'never'],
        'style/function-paren-newline': ['warn', 'consistent'],
        'style/generator-star-spacing': 'warn',
        'style/indent-binary-ops': ['warn', 2],
        'style/indent': ['warn', 2, {
          SwitchCase: 1,
          VariableDeclarator: 'first',
          offsetTernaryExpressions: true,
          ignoreComments: false,
          ignoredNodes: [
            'TSUnionType',
            'TSIntersectionType',
            'TSTypeParameterInstantiation',
            'FunctionExpression > .params[decorators.length > 0]',
            'FunctionExpression > .params > :matches(Decorator, :not(:first-child))',
          ],
        }],
        'style/jsx-closing-bracket-location': ['warn', 'tag-aligned'],
        'style/jsx-closing-tag-location': ['warn', 'tag-aligned'],
        'style/jsx-equals-spacing': ['warn', 'never'],
        'style/jsx-indent-props': ['warn', 2],
        'style/jsx-pascal-case': ['warn', {
          allowNamespace: true,
          ignore: ['[A-Z]+'],
        }],
        'style/jsx-quotes': ['warn', 'prefer-single'],
        'style/jsx-self-closing-comp': 'warn',
        'style/jsx-tag-spacing': ['warn', {
          beforeClosing: 'never',
          beforeSelfClosing: 'always',
        }],
        'style/key-spacing': 'warn',
        'style/keyword-spacing': 'warn',
        'style/member-delimiter-style': 'warn',
        'style/no-extra-semi': 'warn',
        'style/no-multi-spaces': 'warn',
        'style/no-tabs': 'warn',
        'style/no-trailing-spaces': 'warn',
        'style/no-whitespace-before-property': 'warn',
        'style/object-curly-spacing': ['warn', 'always'],
        'style/operator-linebreak': ['warn', 'before'],
        'style/quote-props': ['warn', 'as-needed'],
        'style/quotes': ['warn', 'single'],
        'style/rest-spread-spacing': ['warn', 'never'],
        'style/semi-spacing': 'warn',
        'style/semi-style': 'warn',
        'style/semi': 'warn',
        'style/space-before-blocks': ['warn', 'always'],
        'style/space-before-function-paren': ['warn', { named: 'never' }],
        'style/space-infix-ops': ['warn', { int32Hint: false }],
        'style/space-unary-ops': 'warn',
        'style/switch-colon-spacing': 'warn',
        'style/type-annotation-spacing': 'warn',
        'style/type-generic-spacing': 'warn',
        'style/type-named-tuple-spacing': 'warn',
        'style/yield-star-spacing': ['warn', {
          before: true,
          after: false,
        }],
      },
    },
    {
      name: 'silvecor/javascript/regexp',
      plugins: {
        regexp: pluginRegExp,
      },
      /// keep-sorted
      rules: {
        'regexp/confusing-quantifier': 'warn',
        'regexp/control-character-escape': 'error',
        'regexp/match-any': 'error',
        'regexp/negation': 'error',
        'regexp/no-contradiction-with-assertion': 'error',
        'regexp/no-dupe-characters-character-class': 'error',
        'regexp/no-dupe-disjunctions': 'error',
        'regexp/no-empty-alternative': 'warn',
        'regexp/no-empty-capturing-group': 'error',
        'regexp/no-empty-character-class': 'error',
        'regexp/no-empty-group': 'error',
        'regexp/no-empty-lookarounds-assertion': 'error',
        'regexp/no-empty-string-literal': 'error',
        'regexp/no-escape-backspace': 'error',
        'regexp/no-extra-lookaround-assertions': 'error',
        'regexp/no-invalid-regexp': 'error',
        'regexp/no-invisible-character': 'error',
        'regexp/no-lazy-ends': 'warn',
        'regexp/no-legacy-features': 'error',
        'regexp/no-misleading-capturing-group': 'error',
        'regexp/no-misleading-unicode-character': 'error',
        'regexp/no-missing-g-flag': 'error',
        'regexp/no-non-standard-flag': 'error',
        'regexp/no-obscure-range': 'error',
        'regexp/no-optional-assertion': 'error',
        'regexp/no-potentially-useless-backreference': 'warn',
        'regexp/no-super-linear-backtracking': 'error',
        'regexp/no-trivially-nested-assertion': 'error',
        'regexp/no-trivially-nested-quantifier': 'error',
        'regexp/no-unused-capturing-group': 'error',
        'regexp/no-useless-assertions': 'error',
        'regexp/no-useless-backreference': 'error',
        'regexp/no-useless-character-class': 'error',
        'regexp/no-useless-dollar-replacements': 'error',
        'regexp/no-useless-escape': 'error',
        'regexp/no-useless-flag': 'warn',
        'regexp/no-useless-lazy': 'error',
        'regexp/no-useless-non-capturing-group': 'error',
        'regexp/no-useless-quantifier': 'error',
        'regexp/no-useless-range': 'error',
        'regexp/no-useless-set-operand': 'error',
        'regexp/no-useless-string-literal': 'error',
        'regexp/no-useless-two-nums-quantifier': 'error',
        'regexp/no-zero-quantifier': 'error',
        'regexp/optimal-lookaround-quantifier': 'warn',
        'regexp/optimal-quantifier-concatenation': 'error',
        'regexp/prefer-character-class': 'error',
        'regexp/prefer-d': 'error',
        'regexp/prefer-plus-quantifier': 'error',
        'regexp/prefer-predefined-assertion': 'error',
        'regexp/prefer-question-quantifier': 'error',
        'regexp/prefer-range': 'error',
        'regexp/prefer-set-operation': 'error',
        'regexp/prefer-star-quantifier': 'error',
        'regexp/prefer-unicode-codepoint-escapes': 'error',
        'regexp/prefer-w': 'error',
        'regexp/simplify-set-operations': 'error',
        'regexp/sort-flags': 'error',
        'regexp/strict': 'error',
        'regexp/use-ignore-case': 'error',
      },
    },
  ];
}
